# 新版本的 docker-compose 已经不需要版本字段
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_spring
    ports:
      - "8080:8080"
    networks:
      - test_net
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: test_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=euphemism
    volumes:
      - ./data/mysql/initsql:/docker-entrypoint-initdb.d
      - ./data/mysql/db:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql
    networks:
      - test_net

networks:
  test_net:
    driver: bridge
