spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/euphemism?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true

logging:
  level:
    sast.freshcup.mapper: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: fun.sast.word.entity
  mapper-locations: classpath*:/mapper/*.xml